// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIt4iVE8OeI4twloTCN1rMyhL6E_3hM0U',
    appId: '1:71064898991:web:604d4093a8478e8f40b35a',
    messagingSenderId: '71064898991',
    projectId: 'alertas-seguranca',
    authDomain: 'alertas-seguranca.firebaseapp.com',
    storageBucket: 'alertas-seguranca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhHFexNHLN5x3xAPCNd4YGGgFlly6EM48',
    appId: '1:71064898991:android:11a5ef3749b9224540b35a',
    messagingSenderId: '71064898991',
    projectId: 'alertas-seguranca',
    storageBucket: 'alertas-seguranca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfAYeVDg-FuyZdqOdUngtgNGxGQZhyOHM',
    appId: '1:71064898991:ios:27b0f306fcf7416f40b35a',
    messagingSenderId: '71064898991',
    projectId: 'alertas-seguranca',
    storageBucket: 'alertas-seguranca.firebasestorage.app',
    iosBundleId: 'com.example.atividade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfAYeVDg-FuyZdqOdUngtgNGxGQZhyOHM',
    appId: '1:71064898991:ios:27b0f306fcf7416f40b35a',
    messagingSenderId: '71064898991',
    projectId: 'alertas-seguranca',
    storageBucket: 'alertas-seguranca.firebasestorage.app',
    iosBundleId: 'com.example.atividade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIt4iVE8OeI4twloTCN1rMyhL6E_3hM0U',
    appId: '1:71064898991:web:3992361c0048ecb740b35a',
    messagingSenderId: '71064898991',
    projectId: 'alertas-seguranca',
    authDomain: 'alertas-seguranca.firebaseapp.com',
    storageBucket: 'alertas-seguranca.firebasestorage.app',
  );
}
